version: "3.8"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_USER: note_app_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: note_db
    ports:
      - 3306:3306
    volumes:
      - ./.docker/db-volume:/var/lib/mysql
      - ./.docker/db-initialization:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/api/src
    environment:
      DB_USER: note_app_user
      DB_PASSWORD: password
      DB_DATABASE: note_db
      DB_HOST: db
    depends_on:
      - db
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    volumes:
      - ./ui/src:/app/src
  