FROM node:latest

COPY package.json \
    package-lock.json \
    tsconfig.json \
    ormconfig.ts \
    /api/
WORKDIR /api
RUN npm ci

# NOTE: this expects to have /src mounted as a volume

CMD [ "npm", "run", "start:dev" ]
